### ISSUE TITLE
Binary for the exporter

### ISSUE THREAD

**Issue by arvindkonar** [Selfnet/prometheus-network-exporter#19]
Is it possible to get a binary file for this?

**Comment by Cellebyte** [comment]
It is possible i think I need some more refactoring before it makes sense to compile it with [https://github.com/indygreg/PyOxidizer](https://github.com/indygreg/PyOxidizer).

If I am done with that I think I can try to compile this exporter with PyOxidizer to make it a single executable.

**Comment by Cellebyte** [comment]
Due to issues with PyOxidizer i used PyInstaller.
Downside is a dependency to glibc.
The executable was build using Debian10 or Archlinux.

If you need it for your own system use PyInstaller yourself.
